config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"
  resources :coffee_drinks
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coffee_drink.rb
class CoffeeDrink < ApplicationRecord
    has_one_attached :picture
    def self.get_all
        CoffeeDrink.all
      end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/coffee_drinks_controller.rb
class CoffeeDrinksController < ApplicationController
  before_action :set_coffee_drink, only: %i[ show edit update destroy ]

  # GET /coffee_drinks or /coffee_drinks.json
  def index
    @coffee_drinks = CoffeeDrink.all
  end

  # GET /coffee_drinks/1 or /coffee_drinks/1.json
  def show
  end

  # GET /coffee_drinks/new
  def new
    @coffee_drink = CoffeeDrink.new
  end

  # GET /coffee_drinks/1/edit
  def edit
  end

  # POST /coffee_drinks or /coffee_drinks.json
  def create
    @coffee_drink = CoffeeDrink.new(coffee_drink_params)

    respond_to do |format|
      if @coffee_drink.save
        format.html { redirect_to coffee_drink_url(@coffee_drink), notice: "Coffee drink was successfully created." }
        format.json { render :show, status: :created, location: @coffee_drink }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @coffee_drink.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coffee_drinks/1 or /coffee_drinks/1.json
  def update
    respond_to do |format|
      if @coffee_drink.update(coffee_drink_params)
        format.html { redirect_to coffee_drink_url(@coffee_drink), notice: "Coffee drink was successfully updated." }
        format.json { render :show, status: :ok, location: @coffee_drink }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @coffee_drink.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coffee_drinks/1 or /coffee_drinks/1.json
  def destroy
    @coffee_drink.destroy

    respond_to do |format|
      format.html { redirect_to coffee_drinks_url, notice: "Coffee drink was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coffee_drink
      @coffee_drink = CoffeeDrink.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def coffee_drink_params
      params.require(:coffee_drink).permit(:name, :recipe, :cost, :picture)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def index; end
   end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coffee_drinks_helper.rb
module CoffeeDrinksHelper
end

app/views/coffee_drinks/_form.html.erb
<%= form_with(model: coffee_drink) do |form| %>
  <% if coffee_drink.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(coffee_drink.errors.count, "error") %> prohibited this coffee_drink from being saved:</h2>

      <ul>
        <% coffee_drink.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :recipe %>
    <%= form.text_field :recipe %>
  </div>

  <div class="field">
    <%= form.label :cost %>
    <%= form.text_field :cost %>
  </div>

  <div class="field">
    <%= form.label :picture %>
    <%= form.file_field(:picture, accept: 'image/png,image/gif,image/jpeg') %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/coffee_drinks/edit.html.erb
<h1>Editing Coffee Drink</h1>

<%= render 'form', coffee_drink: @coffee_drink %>

<%= link_to 'Show', @coffee_drink %> |
<%= link_to 'Back', coffee_drinks_path %>

app/views/coffee_drinks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Coffee Drinks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Recipe</th>
      <th>Cost</th>
      <th>Picture</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @coffee_drinks.each do |coffee_drink| %>
      <tr>
        <td><%= coffee_drink.name %></td>
        <td><%= coffee_drink.recipe %></td>
        <td><%= coffee_drink.cost %></td>
        <td><%= image_tag(coffee_drink.picture) %></td>
        <td><%= link_to 'Show', coffee_drink %></td>
        <td><%= link_to 'Edit', edit_coffee_drink_path(coffee_drink) %></td>
        <td><%= link_to 'Destroy', coffee_drink, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Coffee Drink', new_coffee_drink_path %>

app/views/coffee_drinks/new.html.erb
<h1>New Coffee Drink</h1>

<%= render 'form', coffee_drink: @coffee_drink %>

<%= link_to 'Back', coffee_drinks_path %>

app/views/coffee_drinks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @coffee_drink.name %>
</p>

<p>
  <strong>Recipe:</strong>
  <%= @coffee_drink.recipe %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @coffee_drink.cost %>
</p>

<div>
  <%= image_tag(@coffee_drink.picture) %>
</div>


<%= link_to 'Edit', edit_coffee_drink_path(@coffee_drink) %> |
<%= link_to 'Back', coffee_drinks_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CoffeeShopWebsite</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Shop Homepage - Start Bootstrap Template</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="css/styles.css" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="#!">Sam's Espresso House</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="#!">Home</a></li>
                        <li class="nav-item"><a class="nav-link" href="#!">About</a></li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Shop</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="#!">All Products</a></li>
                                <li><hr class="dropdown-divider" /></li>
                                <li><a class="dropdown-item" href="#!">Popular Items</a></li>
                                <li><a class="dropdown-item" href="#!">New Arrivals</a></li>
                            </ul>
                        </li>
                    </ul>
                    <form class="d-flex">
                        <button class="btn btn-outline-dark" type="submit">
                            <i class="bi-cart-fill me-1"></i>
                            Cart
                            <span class="badge bg-dark text-white ms-1 rounded-pill">0</span>
                        </button>
                    </form>
                </div>
            </div>
        </nav>
        <!-- Header-->
        <header class="bg-dark py-5">
            <div class="container px-4 px-lg-5 my-5">
                <div class="text-center text-white">
                    <h1 class="display-4 fw-bolder">Sam's Espresso House</h1>
                    <p class="lead fw-normal text-white-50 mb-0">Peruse our daily drink specials</p>
                </div>
            </div>
        </header>
        <!-- Section-->
        <section class="py-5">
            <div class="container px-4 px-lg-5 mt-5">
                <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                    <div class="col mb-5">
                        <% CoffeeDrink.get_all.each do |c| %>
                            <div class="card h-100">
                                <!-- Product image-->
                                <%=image_tag(c.picture)%>
                                <!-- Product details-->
                                <div class="card-body p-4">
                                    <div class="text-center">
                                        <!-- Product name-->
                                        <h5 class="fw-bolder"><%= c.name  %>
                                        </h5>
                                        <!-- Product price-->
                                        $<%= c.cost  %>
                                        <!-- Product description -->
                                        </br>
                                        <%= c.recipe %>
                                    </div>
                                </div>
                                <!-- Product actions-->
                                <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                    <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="#">Add to Cart</a></div>
                                </div>
                                <% end %>
                            </div>
                            
                    </div>
            </div>
        </section>
        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2022</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>